#' Adaptive knockoff
#'
#' This function takes W as an input and outpus the selection set generated by the adaptive knockoff procedure
#'
#' @param w n-by-p martrix of the covariates.
#' @param U p-by-r vector of the side information.
#' @param fdr The target FDR level(s). The default is 0.1.
#' @param offset 0 or 1 (default: 1).
#' @param method The method used for evaluating the probability of being null. The default is random forest.
#'
#' @export



adaptive_knockoff <- function(W,U,fdr = 0.1,offset= 1, method = filter_randomForest,reveal_prop = 0.5,mute = TRUE ){

  #Loading necessary packages
  #packages <- c("knockoff","SNPknock","glmnet","randomForest","doMC")
  packages <- c("gam","glmnet","randomForest","doMC")
  lapply(packages, require, character.only = TRUE)

  #Check input format
  if(is.numeric(X) == 1){
    n = dim(X)[1]
    p = dim(X)[2]
  }else{
    stop("X should be a numeric matrix!")
    }

  if(is.numeric(y) == 1){
    if(length(y) != n) stop('The size of X is not consistent with y!')
  }else{
    stop('y should be a numeric vector!')

  }
  if(is.numeric(U) == 0){
      stop("U should be a numeric matrix!")
  }else{
    U = as.matrix(U)
  }

  if(dim(U)[1]!=p){
    if(dim(U)[2]==P){
      U = t(U)
    }else{
      stop("Please check the dimesion of U!")
    }
  }


 #Run the adaptive knockoff filter
 res = method(W,U,alpha = fdr,offset = offset, reveal_prop = reveal_prop, mute = mute)
 return(res)
}
